export const CART_ADD_ITEM = "CART_ADD_ITEM ";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM ";
export const CART_REMOVE_ALL_ITEMS = "CART_REMOVE_ALL_ITEMS ";
export const DECREASE_ONE_ITEM = "DECREASE_ONE_ITEM ";
export const INCREASE_ONE_ITEM = "INCREASE_ONE_ITEM ";
