// products list constants
export const FETCH_PRODUCT_LIST_START = "FETCH_PRODUCT_LIST_START";
export const FETCH_PRODUCT_LIST_SUCCESS = "FETCH_PRODUCT_LIST_SUCCESS";
export const FETCH_PRODUCT_LIST_FAIL = "FETCH_PRODUCT_LIST_FAIL";

// product details constants
export const FETCH_PRODUCT_DETAILS_START = "FETCH_PRODUCT_DETAILS_START";
export const FETCH_PRODUCT_DETAILS_SUCCESS = "FETCH_PRODUCT_DETAILS_SUCCESS";
export const FETCH_PRODUCT_DETAILS_FAIL = "FETCH_PRODUCT_DETAILS_FAIL";
